### ISSUE TITLE
关于icdar2015_video的问题

### ISSUE THREAD

**Issue by shadow-33** [weijiawu/TransVTSpotter#5]
作者你好，我最近在跟进TransVTSpotter，从官网下载的icdar2015_video测试集中并未提供标注结果，但在你们提供的convert_ICDAR2015video_to_coco.py代码里面有处理测试集xml的代码，想问一下如果你们有测试集标注结果的话，能否提供一下

**Comment by weijiawu** [comment]
convert_ICDAR2015video_to_coco.py并没有处理测试集xml的代码，请仔细查看确认
